### ISSUE TITLE
@semantic-release-plus/docker only supports docker.io

### ISSUE THREAD

**Issue by blakedietz** [semantic-release-plus/semantic-release-plus#56]
## Expected outcome

An image is published to any repository that is not docker.io. For example I should be able to push to a private or self hosted registry.

## Actual outcome

Even when configuring a registryUrl, the code will always push to docker.io.

Note that while although it states that it's pushing to the digital ocean registry in the semantic-release plugin logs,
the actual output of the commands is stating that it's pushing to docker.io. This is because you are not passing the registryUrl to the command that's being run [here](https://github.com/semantic-release-plus/semantic-release-plus/blob/master/packages/plugins/docker/src/lib/publish.ts#L47)

```
...
[4:25:20 PM] [semantic-release] › ✔  Created tag v1.0.0
[4:25:20 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release-plus/docker"
[4:25:20 PM] [semantic-release] [@semantic-release-plus/docker] › ℹ  Pushing version demo-elixir:1.0.0 to registry.digitalocean.com/black-ice
[4:25:20 PM] [semantic-release] [@semantic-release-plus/docker] › ℹ  Pushing version demo-elixir:1 to registry.digitalocean.com/black-ice
[4:25:20 PM] [semantic-release] [@semantic-release-plus/docker] › ℹ  Pushing version demo-elixir:1.0 to registry.digitalocean.com/black-ice
[4:25:20 PM] [semantic-release] [@semantic-release-plus/docker] › ℹ  Pushing version demo-elixir:latest to registry.digitalocean.com/black-ice
[4:25:20 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release-plus/docker"
[4:25:20 PM] [semantic-release] › ✔  Published release 1.0.0 on default channel
The push refers to repository [docker.io/library/demo-elixir]
The push refers to repository [docker.io/library/demo-elixir]
The push refers to repository [docker.io/library/demo-elixir]
The push refers to repository [docker.io/library/demo-elixir]
```

## Steps to reproduce

```
# .github/workflows/semantic-release.yaml
# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t demo-elixir .
          npx semantic-release
```

```js
// releaseconfig.js
module.exports = {
    "branches": ["main"],
    plugins: [
        '@semantic-release/commit-analyzer',
        '@semantic-release/release-notes-generator',
        [
            '@semantic-release-plus/docker',
            {
                name: `demo-elixir`,
                publishLatestTag: true,
                publishMajorTag: true,
                publishMinorTag: true,
                registryUrl: "registry.digitalocean.com/black-ice"
            },
        ],
    ],
};
```

### Proposed fix

https://github.com/blakedietz/semantic-release-plus/blob/master/packages/plugins/docker/src/lib/publish.ts#L47
